# Generated by Django 5.0.3 on 2024-04-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_cinema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='cinema',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
