# Generated by Django 5.0.3 on 2024-04-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_customuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
    ]
